version: '3.5'
services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    hostname: localhost
    restart: unless-stopped
    network_mode: bridge
    # environment:
    #   GITLAB_OMNIBUS_CONFIG: |
    #     external_url 'http://localhost'
    #     gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "80:80"
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
      - ./data/gitlab/logs:/var/log/gitlab

  gitlab-runner:
    build: ./init/docker-ansible/
    image: vnpay-gitlab-runner:alpine
    network_mode: bridge
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - ./data/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

  dns-proxy:
    image: defreitas/dns-proxy-server
    hostname: dns.proxy
    network_mode: bridge
    # ports:
    #   - 5380:5380 
    #   - 53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
       unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'
